// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkLl-WNe7ca9XBqNg5bItvQ1Dhi19OU9s',
    appId: '1:360527594852:web:3a71c1f6383d81e8cfa671',
    messagingSenderId: '360527594852',
    projectId: 'project-b196c',
    authDomain: 'project-b196c.firebaseapp.com',
    storageBucket: 'project-b196c.firebasestorage.app',
    measurementId: 'G-THJSKQS3DZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhnc3HFTi2av9X5sbLXL5UTsUfwU_VV0I',
    appId: '1:360527594852:android:a28b419b03e80873cfa671',
    messagingSenderId: '360527594852',
    projectId: 'project-b196c',
    storageBucket: 'project-b196c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpQRVf6emj9PZWgHkcCTAk1HeQ-bNrWwM',
    appId: '1:360527594852:ios:4ddab495a13db948cfa671',
    messagingSenderId: '360527594852',
    projectId: 'project-b196c',
    storageBucket: 'project-b196c.firebasestorage.app',
    iosBundleId: 'com.example.myTinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpQRVf6emj9PZWgHkcCTAk1HeQ-bNrWwM',
    appId: '1:360527594852:ios:4ddab495a13db948cfa671',
    messagingSenderId: '360527594852',
    projectId: 'project-b196c',
    storageBucket: 'project-b196c.firebasestorage.app',
    iosBundleId: 'com.example.myTinderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkLl-WNe7ca9XBqNg5bItvQ1Dhi19OU9s',
    appId: '1:360527594852:web:08ee49832a9d9985cfa671',
    messagingSenderId: '360527594852',
    projectId: 'project-b196c',
    authDomain: 'project-b196c.firebaseapp.com',
    storageBucket: 'project-b196c.firebasestorage.app',
    measurementId: 'G-381WDMRH0B',
  );
}
